x-common: &common
  restart: unless-stopped
  networks:
    - caddy-shared-network
  dns:
    - 1.1.1.1
    - 8.8.8.8
  labels:
    - "com.centurylinklabs.watchtower.enable=true"

x-common-env: &common-env
  environment:
    - PUID=${UID}
    - PGID=${GID}
    - TZ=${TZ}

services:
  jellyfin:
    <<: *common
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "${UID}:${GID}"
    volumes:
      - ./config/jellyfin:/config
      - ./data/media:/media

  sonarr:
    <<: [*common, *common-env]
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ./config/sonarr:/config
      - ./data:/data

  radarr:
    <<: [*common, *common-env]
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - ./config/radarr:/config
      - ./data:/data

  prowlarr:
    <<: [*common, *common-env]
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - ./config/prowlarr:/config

  qbittorrent:
    <<: [*common, *common-env]
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    volumes:
      - ./config/qbittorrent:/config
      - ./data/torrents:/downloads
    ports:
      - "6881:6881"
      - "6881:6881/udp"

  jellyseerr:
    <<: [*common, *common-env]
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    volumes:
      - ./config/jellyseerr:/app/config

  bazarr:
    <<: [*common, *common-env]
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    volumes:
      - ./config/bazarr:/config
      - ./data:/data

  flaresolverr:
    <<: *common
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}

networks:
  caddy-shared-network:
    external: true
