services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "${UID}:${GID}"
    networks:
      - caddy-shared-network
    volumes:
      - ./config/jellyfin:/config
      - ./data/media:/media
    restart: 'unless-stopped'

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Etc/UTC
    networks:
      - caddy-shared-network
    volumes:
      - ./config/sonarr:/config
      - ./data:/data
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Etc/UTC
    networks:
      - caddy-shared-network
    volumes:
      - ./config/radarr:/config
      - ./data:/data
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Etc/UTC
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - caddy-shared-network
    volumes:
      - ./config/prowlarr:/config
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    networks:
      - caddy-shared-network
    volumes:
      - ./config/qbittorrent:/config
      - ./data/torrents:/downloads
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

networks:
  caddy-shared-network:
    external: true
